name: flutter_appp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  sqflite: ^2.0.2
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  hydrated_bloc: ^8.1.0
  dio: ^4.0.6
  hexcolor: ^2.0.6
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  path_provider: ^2.0.9
  webview_flutter: ^3.0.2
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  fluid_bottom_nav_bar: ^1.3.0
  curved_navigation_bar: ^1.0.3
  image_picker: ^0.8.5
  fluttertoast: ^8.0.9
  desktop_window: ^0.4.0
  pull_to_refresh: ^2.0.0




  #firebase
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  firebase_messaging: ^11.2.13






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.5
flutter_native_splash:
  color:"#ffffff"
  image:assets/images/shoopmon.png
 android:true
 ios:true
 androi_gravity:fill
 ios_contect_mode:scaleAspecFill



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/shoppmoon.png
    - assets/images/shop1.jpg
    - assets/images/shop2.jpg
    - assets/images/shop3.jpg
    - assets/images/shop4.jpg
    - assets/images/shop4.jpg
    - assets/images/Online_Shoping_29.jpg
    - assets/images/social/social_person.jpg
    - assets/images/social/social_person2.jpg
    - assets/images/social/po.jpg
    - assets/images/social/pp.jpg
    - assets/images/shoop.jpg
    - assets/images/shoppmoon logo.png
    - assets/images/social/LightRoom1.gif
    - assets/images/social/white lightroom.gif
    - assets/images/social/LighRoom wh.png



  # To add assets to your application, add an assets section, like this:



  fonts:
      - family: IconDam
        fonts:
          - asset: assets/fonts/icons.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages